# usermod -aG docker gitlab-runner

stages:
  - test
  - build
  - deploy

variables:
  PROJECT_NAME: "xxx"
  PROJECT_VERSION: "1.0"

test:
  stage: test
  script:
    - echo "Clean up start"
    - docker ps -a
    - docker stop $PROJECT_NAME
    - docker rm $PROJECT_NAME
    - docker rmi $PROJECT_NAME:$PROJECT_VERSION
    - echo "Clean up the end of the"
    - sleep 5
  only:
    - master
  tags:
    - builder

build:
  stage: build
  script:
    - echo "build start"
    - docker build . -t $PROJECT_NAME:$PROJECT_VERSION
    - echo "build end"
  only:
    - master  # 分支名或者触发器名字
  tags:
    - builder    # 只有标签为builder的runner才会执行这个

deploy:
  stage: deploy
  script:
    - echo "deploy"
    - docker run -d -p 9501:9501 --network devops --network-alias $PROJECT_NAME --name $PROJECT_NAME $PROJECT_NAME:$PROJECT_VERSION
    - docker ps -a
    - sleep 5
  only:
    - master
  tags:
    - builder