[40001]
other = "The request is frequent."
[40002]
other = "The request timeout."
[40003]
other = "Your request is incorrect."
[40004]
other = "Permission authentication failed."
[50001]
other = "Please select the file after submission."
[50002]
other = "Failed to save file."
[50003]
other = "Please select the file type."