# Why configure to use a single file
# facilitate management

app_name = "laya-go"            ## app_name
http_listen = "0.0.0.0:10080"   ## listen port
run_mode = "debug"              ## mode debug or release
version = "1.0"                 ## version

# cache
## https://github.com/patrickmn/go-cache
[cache]
default = 10    ## 默认过期时间time.Second
clean = 10      ## 多久清理一次缓存单位是time.Second

# mysql
## http://gorm.io/zh_CN/docs/index.html
[mysql]
open = true             ## open
driver = "mysql"        ## 驱动类型,gorm支持的驱动类型有MySQL, PostgreSQL, SQlite, SQL Server
dsn = "root:123456@tcp(127.0.0.1:3306)/laya_go?charset=utf8&parseTime=True&loc=Local"   ## db DSN
maxIdleConn = 10        ## db连接池最大空闲链接数
maxOpenConn = 100       ## db连接池最大连接数
connMaxLifetime = 6     ## 连接池超时时间(单位: time.Hour)

# redis
## https://github.com/go-redis/redis
[redis]
open = true             ## open
db = 0                  ## db
addr = "127.0.0.1:6379" ## addr-链接DSN
pwd = ""                ## pwd-链接密码
poolSize = 5            ## poolSize-链接池大小
maxRetries = 3          ## maxRetries-链接最大重试次数
idleTimeout = 10        ## idleTimeout-空闲链接超时时间(单位：time.Second)

# mongo
## https://github.com/mongodb/mongo-go-driver
[mongo]
open = true         ## open
dsn = "mongodb://root:123456@127.0.0.1:27017,127.0.0.1:27017/?authSource=admin"## DSN
maxIdleConn = 10    ## db连接池最大空闲链接数
maxOpenConn = 100   ## db连接池最大连接数
connMaxLifetime = 6 ## 连接池超时时间(单位: time.Hour)

[i18n]
open = true
defaultLang = "zh"
path = "./config/lang/"

# log
[log]
driver = "file"             ## log driver
path = "./logs/log.info"    ## path
log_level = "INFO"          ## log_level
max_size = 32               ## MB
max_age = 90                ## 保留旧文件的最大天数
max_backups = 300           ## 保留旧文件的最大个数

# mq
[rabbitmq]
[nsq]
[kafka]
