# Why configure to use a single file
# facilitate management

## app_name
app_name = "laya-go"
## listen port
http_listen = "0.0.0.0:10080"
## mode debug or release
run_mode = "debug"
## version
version = "1.0"

# mysql
## http://gorm.io/zh_CN/docs/index.html
[mysql]
## open
open = true
## 驱动类型,gorm支持的驱动类型有MySQL, PostgreSQL, SQlite, SQL Server
driver = "mysql"
## db DSN
dsn = "root:123456@tcp(127.0.0.1:3306)/laya_go?charset=utf8&parseTime=True&loc=Local"
## db连接池最大空闲链接数
maxIdleConn = 10
## db连接池最大连接数
maxOpenConn = 100
## 连接池超时时间(单位: time.Hour)
connMaxLifetime = 6

# redis
## https://github.com/go-redis/redis
[redis]
## open
open = true
## db
db = 0
## addr-链接DSN
addr = "127.0.0.1:6379"
## pwd-链接密码
pwd = "123456"
## poolSize-链接池大小
poolSize = 5
## maxRetries-链接最大重试次数
maxRetries = 3
## idleTimeout-空闲链接超时时间(单位：time.Second)
idleTimeout = 10

# mongo
## https://github.com/mongodb/mongo-go-driver
[mongo]
## open
open = true
## DSN
dsn = "mongodb://root:123456@127.0.0.1:27017,127.0.0.1:27017/?authSource=admin"
## db连接池最大空闲链接数
maxIdleConn = 10
## db连接池最大连接数
maxOpenConn = 100
## 连接池超时时间(单位: time.Hour)
connMaxLifetime = 6

[i18n]
open = true
defaultLang = "zh"
path = "./config/lang/"

# log
[log]
## log driver
driver = "file"
## path
path = "./logs/log.info"
## log_level
log_level = "INFO"
## MB
max_size = 32
## 保留旧文件的最大天数
max_age = 90
## 保留旧文件的最大个数
max_backups = 300

# mq
[rabbitmq]
[nsq]
[kafka]
