# mysql config 单库配置,目前不支持读写分离和多库连接

## 驱动类型,gorm支持的驱动类型有MySQL, PostgreSQL, SQlite, SQL Server
## https://gorm.io/zh_CN/docs/connecting_to_the_database.html
driver = "mysql"
## open
open = true
## db DSN
dsn = "root:123456@tcp(127.0.0.1:3306)/laya_go?charset=utf8&parseTime=True&loc=Local"
## db连接池最大空闲链接数
maxIdleConn = 10
## db连接池最大连接数
maxOpenConn = 100
## 连接池超时时间(单位: time.Hour)
connMaxLifetime = 6
