[RequestFrequentUuid]
other = "The request is frequent."
[RequestFrequentTime]
other = "The request timeout."
[RequestFrequentSign]
other = "Your request is incorrect."
[TokenErr]
other = "Permission authentication failed."