[RequestFrequentUuid]
other = "请求频繁！"
[RequestFrequentTime]
other = "请求超时！"
[RequestFrequentSign]
other = "您的请求有误！"
[TokenErr]
other = "权限验证失败！"
[NoFile]
other = "请选择文件后在提交！"
[SaveUploadedFail]
other = "保存文件失败！"
[NoFileType]
other = "请选择文件类型！"