# mongodb 配置


## open
open = true

## DSN
## mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
## https://docs.mongodb.com/manual/reference/connection-string/
dsn = "mongodb://root:123456@127.0.0.1:27017,127.0.0.1:27017/?authSource=admin"

## db连接池最大空闲链接数
maxIdleConn = 10

## db连接池最大连接数
maxOpenConn = 100

## 连接池超时时间(单位: time.Hour)
connMaxLifetime = 6
